title: ktsmmxl's Homepage
page-top-title: Zhongshang Li
top-section-bg-text: Physics & Astronomy & Photography & Outdoors
home-subtitle: Zhongshang Li&ensp;|&ensp;李忠尚&ensp;|&ensp;ktsmmxl&ensp;|&ensp;崆峒山马门溪龙
copyright-text: '&copy; Zhongshang Li 2026. All Rights Reserved.'
